### ISSUE TITLE
How to build this repo?

### ISSUE THREAD

**Issue by levindu** [rockchip-linux/xserver#1]
I've installed a bunch of dev packages in the debian system built by [rk-rootfs-build](https://github.com/rockchip-linux/rk-rootfs-build), yet cannot solve the following for the time being:

```
../../../glamor/glamor_egl.c: In function 'glamor_egl_create_textured_pixmap_from_gbm_bo':
../../../glamor/glamor_egl.c:311:2: error: implicit declaration of function 'gbm_bo_unref' [-Werror=implicit-function-declaration]
  gbm_bo_unref(pixmap_priv->bo);
  ^
../../../glamor/glamor_egl.c:311:2: warning: nested extern declaration of 'gbm_bo_unref' [-Wnested-externs]
../../../glamor/glamor_egl.c:325:5: error: implicit declaration of function 'gbm_bo_ref' [-Werror=implicit-function-declaration]
     gbm_bo_ref(bo);
```

Google `gbm_bo_ref`, found nothing.

**Comment by wzyy2** [comment]
Those functions are implemented in libmali to support glmaor.
Try extract gbm.h from libmali-rk-dev_1.4-4_armhf.deb.

**Comment by wzyy2** [comment]
a simple guide

http://rockchip.wikidot.com/porting-os

**Comment by levindu** [comment]
Good stuff. Thank you!

**Comment by hizukiayaka** [comment]
You could also use the debian build system to build, it is located at branch rockchip-1.18
