### ISSUE TITLE
Building with --enable-dmx

### ISSUE THREAD

**Issue by Dante4** [rockchip-linux/xserver#13]
If use command from there 
http://opensource.rock-chips.com/wiki_Distribution
i.e.

> ./autogen.sh --prefix=/usr --enable-aiglx --enable-composite --enable-record --enable-xv --enable-xvmc --enable-dga --enable-screensaver --enable-xdmcp --enable-xdm-auth-1 --enable-glx --enable-dri --enable-dri2 --enable-glamor --enable-dri3 --enable-libdrm --enable-present --enable-xinerama --enable-xf86vidmode --enable-xace --enable-xselinux --enable-xfree86-utils --enable-xwayland --enable-systemd-logind --with-systemd-daemon --enable-suid-wrapper --enable-dmx --enable-xvfb --enable-xnest --enable-kdrive --enable-xephyr --enable-xmir --with-sha1=libgcrypt --enable-xcsecurity  --with-log-dir=/var/log

build proccess fails with 
```
make[5]: Entering directory '/root/xserver/hw/dmx/config'
  CC       dmxparse.o
  LEX      scanner.c
  CC       dmxprint.o
  CC       parser.o
  CC       dmxcompat.o
  CC       dmxconfig.o
  CC       strlcpy.o
  CC       xdmxconfig-xdmxconfig.o
  CC       xdmxconfig-dmxlog.o
  CC       xdmxconfig-Canvas.o
  CC       vdltodmx.o
  CC       dmxtodmx.o
  CC       scanner.o
gcc: error: scanner.c: No such file or directory
gcc: fatal error: no input files
```

**Comment by JeffyCN** [comment]
we are using 1.20.4 now, and cannot repro this issue.
