### ISSUE TITLE
Update package version strings

### ISSUE THREAD

**Issue by MichaIng** [rockchip-linux/xserver#14]
Would it be possible to update the package version strings? It appears that on Debian Buster, `apt-get upgrade` overwrites the current RockChip packages with the ones from Debian repository. This is actually strange since the version strings match from what I see: https://packages.debian.org/buster/xserver-xorg-core
Of course `apt-mark hold` can block it, but it would be better/failsafe to have a higher/same version string to prevent apt from even trying.

Related issue is that the X.org modesetting from Debian repo does not support the AccelMethod "exa", does it? At least the man page states only "none" or "glamor" being supported: https://manpages.debian.org/buster/xserver-xorg-core/modesetting.4.en.html#CONFIGURATION_DETAILS
So a package override will break the X.org configuration with AccelMethod exa.
- **EDIT: On the other hand, the Debian repo package ships `/usr/lib/xorg/modules/libexa.so`, so probably the man pages are just outdated?**

And generally it is correct that the provided X.org packages (https://github.com/rockchip-linux/rk-rootfs-build/tree/master/packages/arm64/xserver) provide better GPU acceleration support for RockChip GPUs with Mali drivers installed, compared to the ones from Debian repo?

**Comment by JeffyCN** [comment]
@Caesar-github , please check it

**Comment by JeffyCN** [comment]
currently we have lots of custom packages, and we are prefer to use them instead of the debian's official ones.
here's the newest try to hold them:
https://github.com/rockchip-linux/rk-rootfs-build/commit/0a5af5b1795f2949d7e0d7f2e7f71089d6892e39
