### ISSUE TITLE
xserver EQ overflow

### ISSUE THREAD

**Issue by pebauer68** [rockchip-linux/xserver#2]
Using mate or xfce4 Desktop with RK-RFS (linaro-alip Debian 9) RFS form 15.10.2016 (apt-get dist-upgrade was done) the following output is in Xorg.0.log:
-most of the time a login to the desktop is not possible 
(EE) [mi] EQ overflow continuing.  900 events have been dropped.
(EE) 
(EE) Backtrace:
(EE) 
(EE) [mi] EQ overflow continuing.  1000 events have been dropped.
(EE) [mi] No further overflow reports will be reported until the clog is cleared.
(EE)

**Comment by wzyy2** [comment]
I used  a xfce4 desktop and don't get this problem
```
apt-get remove lxde-core
apt-get install xfce4
startxfce4
```

It seems everything work fine.

**Comment by pebauer68** [comment]
Please do some extended tests including reboots and using desktop(starting X11 applications) for some hours. The issue might not appear immedeatly.

**Comment by wzyy2** [comment]
/etc/X11/xorg.conf.d/20-modesetting.conf

You can close glamor by change Option "AccelMethod" form  "glamor" to  "glamor1".

**Comment by wzyy2** [comment]
I install it in my chromebook and using for some hours but i still didn't get this problem...
Can you try this new image?

https://drive.google.com/file/d/0BwAJtUrQohwXV1ZLbzA4VGZKRDg/view?usp=sharing

**Comment by Avagetto** [comment]
I have the same problem as and Peter, i tried xfce4 and mate DE.  It can happen when you launch any app, mousepad, filemanager, termial....

I dont  know does Jacob Chen shared logs or not, i will attach them here.
I have 2 different error when using  **xserver-xorg-input-evdev** and **xserver-xorg-input-all** packages. 

Xorg.0.log with installed package **xserver-xorg-input-evdev** and without **xserver-xorg-input-all** i have same problem as wrote Peter. DE freezes but mouse moving. Bad, but moving.
http://pastebin.com/57NaKpiH

Xorg.0.log with installed package **xserver-xorg-input-all** and without **xserver-xorg-input-evdev**. DE freezes at all. mouse not moving at all. 

> [103019.771] (II) SYN_DROPPED event from "2.4GHz keyboard and mouse" - some input events have been lost.
> [106020.524] (II) SYN_DROPPED event from "2.4GHz keyboard and mouse" - some input events have been lost.
> [106211.801] (II) SYN_DROPPED event from "2.4GHz keyboard and mouse" - some input events have been lost.
> [106312.432] (II) SYN_DROPPED event from "2.4GHz keyboard and mouse" - some input events have been lost.

http://pastebin.com/T0YVZGts

I`m tried reproduce bug with  xserver provided by debian, but without successful. Bug appear after was installed xserver-common_1.18.99-2_all and  xserver-xorg-core_1.18.99-2_armhf  provided by rockchip.

Thanks for image, i will try it now.

**Comment by wzyy2** [comment]
after reboot..The issue appeared...Let me see...

**Comment by wzyy2** [comment]
Hi Avagetto,
This image also have this bug..

**Comment by wzyy2** [comment]
I think it should go back to 1.18.21.
1.18.99 is buggy,  there are many known bugs.

**Comment by wzyy2** [comment]
I think it should go back to 1.18.21.
1.18.99 is buggy,  there are many known bugs.

**Comment by wzyy2** [comment]
We will go back to 1.18.21 rather than fix it in 1.18.99 .
1.18.99 is buggy,  there are many known bugs.

**Comment by Avagetto** [comment]
Does you test 1.18.21-2? i have the same problem with this version of xserver also.

**Comment by wzyy2** [comment]
Did " EQ overflow"  also happned in 1.18.21?

1.18.99.1 in this repo is checkout from xserver develop branch.
1.18.21 is a stable branch but we have some bugs with glamor in it.

**Comment by wzyy2** [comment]
Can you try xserver deb in below link?
https://drive.google.com/drive/folders/0BwAJtUrQohwXUVJYVnA5Z3YydGc?usp=sharing

**Comment by pebauer68** [comment]
I did not see EQ overflow with 1.18.21 with Debian 8 RFS and using the Mate
desktop.

**Comment by Avagetto** [comment]
Yes, it happens 1.18.21-2.
I`m used bin packages from here:
https://github.com/rockchip-linux/rk-rootfs-build/tree/479ff5165c3915f9c520405cfa7af2672a0cc8bc/packages/armhf

With version 1.18.21-3 , from link what you give, problem disappeared. But i have problem with image, i have diffusion with the panel . I don't seen this problem before.
https://postimg.org/image/714uff40z/

**Comment by wzyy2** [comment]
: )
That's why we don't use 1.18.21..

**Comment by wzyy2** [comment]
Hi,
I update new xserver.
https://github.com/rockchip-linux/rk-rootfs-build/commit/0c83fc24b93a70ed42b49b638a180f0618e9c9ec

Are there anyone can help test it?

**Comment by pebauer68** [comment]
Yes, I will Test in the evening

Am 10.11.2016 12:00 nachm. schrieb "陈豪 | Jacob Chen" <
notifications@github.com>:

**Comment by pebauer68** [comment]
1.18.21-4 looks ok on the MiQi device running Debian 9 and the Mate Desktop, I did not see EQ overflow yesterday - We still need to test other Desktop environments, too. Thank you

**Comment by Avagetto** [comment]
Yes, this version look good. i doesn't seen bug with freezing and image diffusion's yet.
