### ISSUE TITLE
xserver glamor

### ISSUE THREAD

**Issue by fjyihan** [rockchip-linux/xserver#3]
xserver with glamor ，大量绘图测试，存在内存泄漏问题

**Comment by wzyy2** [comment]
能提供一下测试方法以及对应的版本环境吗？

我们是有know issue，就是libmali r13版本存在内存泄漏，所以你如果用的是libmali r13,是存在问题的
我们这里update到r13主要是为了一些feature，稳定性的话再退回到r9

**Comment by fjyihan** [comment]
测试方式用的是自己编写的2dbench 应用，ubuntu 16.04 
用的是libmali r13 know issue哪里可以找到？

**Comment by wzyy2** [comment]
你可以换成这个
https://github.com/rockchip-linux/rk-rootfs-build/blob/master/packages/armhf/libmali/libmali-rk-midgard-r9p0-r0p0_1.5-4_armhf.deb
