### ISSUE TITLE
lag of draging window in xserver-1.19.3 and oom with xserver-1.18.4 due to draw

### ISSUE THREAD

**Issue by alandingbc** [rockchip-linux/xserver#8]
There are some problems on my firefly-rk3288 board.

1. On Ubuntu 16.04 with xserver-1.18.4
  when lots of drawing on my gtk app, it will quickly get oom by xserver process and oom_killer triggered.
  I try to replace the libmali with different versions, libmali-midgard-t76x-r13p0-r0p0.so, libmali-midgard-t76x-r9p0-r0p0.so and the lastest libmali-midgard-t76x-r14p0-r0p0.so. It seems the libmali doesn't cause the buggy.
  Then I force to update the xserver with 1.19.3. Here is no oom anymore, but the version is too hight and caused some problems of depency.

2. On Debian 9 with xserver-1.19.3
  No oom, however, I could feel lag obviously when dragging the window. It happened on the Ubuntu 16.04 with the same version 1.19.3 too. I have checked the Xorg.log, the glamor initialized.

3. On Ubuntu 18.04
  Recently, I try to build the Ubuntu 18.04 which default version of the xserver is updated to 1.19.6. It's no oom too and works smoothly. So I guess that there is buggy on the old xserver. But it couldn't initialize glamor and glmark-es2 couldn't invoke eglInitialize correctly, so it could be incompatible with the libmali or couldn't invoke egl as first.

I don't know too much about xserver, anyone could give me some useful info with great thanks.
I really need a stable distribution.

**Comment by JeffyCN** [comment]
The old version is dead.
