### ISSUE TITLE
Full screen presentations broken in LibreOffice

### ISSUE THREAD

**Issue by nedrichards** [rockchip-linux/xserver#9]
As noted under this commit by @dsd : https://github.com/rockchip-linux/xserver/commit/fe4d141fc7fe2d7ec13ce5093a8d746c406115dd

> This commit breaks Libreoffice fullscreen presentations, tested under mutter and metacity. The full screen presentation simply does not appear. Reverting this commit makes it work fine.

> Are you trying to unredirect fullscreen windows in order to improve performance? You should not need to do this here. There is a well defined standard for that (_NET_WM_BYPASS_COMPOSITOR) and also compositors such as mutter will intelligently unredirect fullscreen windows when the right conditions are met.

> If you do want to implement some kind of magic unredirect in the X server, I think you would need to follow the "unredirect" codepath that already exists in this function (calling compSetParentPixmap and compRestoreWindow) in order for the window to become visible.

**Comment by JeffyCN** [comment]
The old version is dead.
